substitutions:
  device_name: slimmelezer

esphome:
  name: ${device_name}
  comment: "P1 module to read smart meter"
  name_add_mac_suffix: false
  project:
    name: p1reader.slimmelezer-component
    version: "1.0"

esp8266:
  board: d1_mini
  restore_from_flash: true

external_components:
  - source: ../esphome-components
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: ${device_name}
  #   ap_timeout: 15s
  #   password: !secret fallback_ap_password

  reboot_timeout: 5min
  domain: .local

captive_portal:

# Enable logging
# baud_rate: 0, stops the logger using UART logging so it does not use the hardware one that might be needed for the
# actual device to work properly
# And avoid some wear on the flash for device longevity
logger:
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false
  level: INFO
  
# Enable Home Assistant API
api:
          
ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80
 
uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 3072

binary_sensor:
  - platform: status
    name: "SlimmeLezer - Status"  

p1reader:
  - id: p1reader_slimmelezer
    uart_id: uart_bus
#    buffer_size: 3072
#    protocol: ascii

sensor:
  - platform: uptime
    name: "SlimmeLezer - Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

  - platform: wifi_signal
    name: "SlimmeLezer - Wi-Fi Signal"
    update_interval: 60s
    icon: mdi:wifi

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    cumulative_active_import:
      name: "Cumulative Active Import"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    cumulative_active_export:
      name: "Cumulative Active Export"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    cumulative_reactive_import:
      name: "Cumulative Reactive Import"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    cumulative_reactive_export:
      name: "Cumulative Reactive Export"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_active_import:
      name: "Momentary Active Import"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_active_export:
      name: "Momentary Active Export"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_reactive_import:
      name: "Momentary Reactive Import"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_reactive_export:
      name: "Momentary Reactive Export"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_active_import_l1:
      name: "Momentary Active Import Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_active_export_l1:
      name: "Momentary Active Export Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_active_import_l2:
      name: "Momentary Active Import Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_active_export_l2:
      name: "Momentary Active Export Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_active_import_l3:
      name: "Momentary Active Import Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_active_export_l3:
      name: "Momentary Active Export Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_reactive_import_l1:
      name: "Momentary Reactive Import Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_reactive_import_l2:
      name: "Momentary Reactive Import Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_reactive_import_l3:
      name: "Momentary Reactive Import Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_reactive_export_l1:
      name: "Momentary Reactive Export Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_reactive_export_l2:
      name: "Momentary Reactive Export Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    momentary_reactive_export_l3:
      name: "Momentary Reactive Export Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    voltage_l1:
      name: "Voltage Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    voltage_l2:
      name: "Voltage Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    voltage_l3:
      name: "Voltage Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    current_l1:
      name: "Current Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    current_l2:
      name: "Current Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_slimmelezer
    current_l3:
      name: "Current Phase 3"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "SlimmeLezer - IP Address"
    ssid:
      name: "SlimmeLezer - Wi-Fi SSID"
    bssid:
      name: "SlimmeLezer - Wi-Fi BSSID"
    mac_address:
      name: "SlimmeLezer - Wi-Fi MAC Address"
    dns_address:
      name: "SlimmeLezer - DNS Address"

  - platform: version
    name: "SlimmeLezer - ESPHome Version"
    hide_timestamp: false